### ISSUE TITLE
Failed opening required string.php

### ISSUE THREAD

**Issue by skorotkiewicz** [SjonHortensius/TooBasic#1]
PHP Fatal error:  require(): Failed opening required '/home/dev/too/TooBasic/string.php' (include_path='.:/usr/share/php:/usr/share/pear') in /home/dev/too/index.php on line 5

Debian.

**Comment by SjonHortensius** [comment]
Thanks for your report. Can you show what is in your `index.php` on line 5 as it isn't part of this framework? This might be a bug in my autoloader but I'm not sure
